fix: splat operator for PHP 7.4
oat-sa/extension-tao-delivery-rdf pull request #487
Opened 2024-06-24 14:51 UTC by pnal

2024-06-25 09:28 UTC, tikhanovichA approved these changes
LGTM

2024-06-26 14:20 UTC, bartlomiejmarszal requested changes
This is unusual to try catch in test. Why do you need this?

2024-06-26 14:20 UTC, bartlomiejmarszal commented on test/unit/model/DataStore/DeliverySyncTaskTest.php
> +                ['resourceId' => $mockDelivery->getUri(), 'fileSystemId' => 'dataStore'], // check assoc array
```suggestion
                [
                'resourceId' => $mockDelivery->getUri(),
                'fileSystemId' => 'dataStore'
                ], // check assoc array
```

2024-06-26 15:51 UTC, pnal commented on test/unit/model/DataStore/DeliverySyncTaskTest.php
> +                ['resourceId' => $mockDelivery->getUri(), 'fileSystemId' => 'dataStore'], // check assoc array
to fail the same case on PHP 7.4

2024-06-27 08:03 UTC, Karol-Stelmaczonek approved these changes
- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2024-06-27 09:45 UTC, merged